version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    command: start-dev
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
